version: '3'

services:
  # Serviço do banco de dados MySQL
  db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: examplepassword
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepassword

  # Serviço da aplicação web
  app:
    build: .
    ports:
      - "80:80"  # Corrigido para mapear a porta 80 do aplicativo para a porta 80 do host
    depends_on:
      - db  # Garante que o serviço do banco de dados seja iniciado primeiro
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  db_data:
